name: Clojure CI Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: linux

    env:
      CI_ENV: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: https://github.com/actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Set up Clojure
        uses: https://github.com/DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Formatting
        run: clojure -M:cljfmt check
      - name: Linting
        run: clojure -M:clj-kondo --lint src --lint test --lint dev
